/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travel;

import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDate; 
import java.util.Date;
import java.time.Instant;
import java.time.ZoneId;

/**
 *
 * @author nambi
 */
public class Flight extends javax.swing.JFrame {

    /**
     * Creates new form Flight
     */
     public Container getContentPane() {
        return super.getContentPane(); //To change body of generated methods, choose Tools | Templates.
    }
    public Flight() {
        initComponents();
        this.getContentPane().setBackground(Color.ORANGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fblbl = new javax.swing.JLabel();
        optnlbl = new javax.swing.JLabel();
        Radoneway = new javax.swing.JRadioButton();
        Radrndtrip = new javax.swing.JRadioButton();
        sdlbl = new javax.swing.JLabel();
        Combsrc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Combdest = new javax.swing.JComboBox<>();
        classlbl = new javax.swing.JLabel();
        Radeco = new javax.swing.JRadioButton();
        Radbsns = new javax.swing.JRadioButton();
        Radfirst = new javax.swing.JRadioButton();
        Datelbl = new javax.swing.JLabel();
        Date = new com.toedter.calendar.JDateChooser();
        Flightsrchbtn = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fblbl.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        fblbl.setForeground(new java.awt.Color(204, 0, 0));
        fblbl.setText("FLIGHT BOOKING");

        optnlbl.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        optnlbl.setForeground(new java.awt.Color(204, 0, 0));
        optnlbl.setText("Select an option:");

        Radoneway.setText("One Way");

        Radrndtrip.setText("Round Trip");

        sdlbl.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        sdlbl.setForeground(new java.awt.Color(204, 0, 0));
        sdlbl.setText("Select Source and Destination:");

        Combsrc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BANGALORE", "DELHI", "MUMBAI", "CHENNAI", "KOLKATA", "GOA", "HYDERABAD" }));
        Combsrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombsrcActionPerformed(evt);
            }
        });

        jLabel4.setText("To");

        Combdest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BANGALORE", "DELHI", "MUMBAI", "CHENNAI", "KOLKATA", "GOA", "HYDERABAD" }));
        Combdest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombdestActionPerformed(evt);
            }
        });

        classlbl.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        classlbl.setForeground(new java.awt.Color(204, 0, 0));
        classlbl.setText("Select Class:");

        Radeco.setText("Economy");

        Radbsns.setText("Business");

        Radfirst.setText("First");

        Datelbl.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        Datelbl.setForeground(new java.awt.Color(204, 0, 0));
        Datelbl.setText("Select Date:");

        Flightsrchbtn.setText("PROCEED");
        Flightsrchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightsrchbtnActionPerformed(evt);
            }
        });

        Cancel.setText("CANCEL");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(fblbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(Flightsrchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                            .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sdlbl)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Combsrc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(Combdest, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(optnlbl)
                                        .addComponent(Radoneway))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Radrndtrip)
                                    .addGap(29, 29, 29))
                                .addComponent(classlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Radeco)
                                    .addGap(57, 57, 57)
                                    .addComponent(Radbsns)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Radfirst))
                                .addComponent(Datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fblbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optnlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Radoneway)
                    .addComponent(Radrndtrip))
                .addGap(18, 18, 18)
                .addComponent(sdlbl)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combsrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Combdest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(classlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Radeco)
                    .addComponent(Radbsns)
                    .addComponent(Radfirst))
                .addGap(18, 18, 18)
                .addComponent(Datelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Flightsrchbtn)
                    .addComponent(Cancel))
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CombsrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombsrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CombsrcActionPerformed

    private void FlightsrchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightsrchbtnActionPerformed
        // TODO add your handling code here:
        /*if((((Radoneway.isSelected())&&(Radrndtrip.isSelected()))==false)||(Combsrc.getSelectedItem().toString().isEmpty())||(Combdest.getSelectedItem().toString().isEmpty())||(((Radeco.isSelected())&&(Radbsns.isSelected())&&(Radfirst.isSelected()))==false)||(Date.getDate().toString().isEmpty()))
        {
            JOptionPane.showMessageDialog(null, "Field is Empty");
        }*/
        //else
        //{
        LocalDate date1 = java.time.LocalDate.now();
        Date date = Date.getDate();
        Instant instant = date.toInstant();
        LocalDate date2 = instant.atZone(ZoneId.systemDefault()).toLocalDate();
        if(date2.compareTo(date1)<0)
        {
            JOptionPane.showMessageDialog(null, "The date chosen is before today's date!");
        }
        else
        {
        if((Combsrc.getSelectedItem().toString())==(Combdest.getSelectedItem().toString()))
        {
            JOptionPane.showMessageDialog(null, "Your source and Destination are the same!");
        }
        else if(Radoneway.isSelected() && Radrndtrip.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Both one way and round trip are selected!");
        }
        else if((Radeco.isSelected() && Radbsns.isSelected()) || (Radeco.isSelected() && Radfirst.isSelected()) || (Radbsns.isSelected() && Radfirst.isSelected()))
        {
            JOptionPane.showMessageDialog(null, "Two options are selected in class");
        }
        else if(Radeco.isSelected() && Radbsns.isSelected() && Radfirst.isSelected())
        {
            JOptionPane.showMessageDialog(null, "More than one option is selected in class");
        }
        else
        {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mini1","root","(Hello123)");
            String sql="insert into flight_det values(?,?,?,?,?,?)";
            PreparedStatement pstmt=conn.prepareStatement(sql);
            pstmt.setString(1,Signup.Txtuser.getText());
            if(Radoneway.isSelected())
            {
                pstmt.setString(2,Radoneway.getText());
            }
            else if(Radrndtrip.isSelected())
            {
                pstmt.setString(2, Radrndtrip.getText());
            }
            pstmt.setString(3,Combsrc.getSelectedItem().toString());
            pstmt.setString(4,Combdest.getSelectedItem().toString());
            if(Radeco.isSelected())
            {
                pstmt.setString(5,Radeco.getText());
            }
            else if(Radbsns.isSelected())
            {
                pstmt.setString(5, Radbsns.getText());
            }
            else if(Radfirst.isSelected())
            {
                pstmt.setString(5,Radfirst.getText());
            }
            pstmt.setString(6,Date.getDate().toString());
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Insertion Successful!");
            conn.close(); 
            dispose();
            new Flight1().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        }
        //}
    }//GEN-LAST:event_FlightsrchbtnActionPerformed

    private void CombdestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombdestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CombdestActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        new Wayoftravel1().setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Cancel;
    public static javax.swing.JComboBox<String> Combdest;
    public static javax.swing.JComboBox<String> Combsrc;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JLabel Datelbl;
    public static javax.swing.JButton Flightsrchbtn;
    private javax.swing.JRadioButton Radbsns;
    private javax.swing.JRadioButton Radeco;
    private javax.swing.JRadioButton Radfirst;
    public static javax.swing.JRadioButton Radoneway;
    public static javax.swing.JRadioButton Radrndtrip;
    private javax.swing.JLabel classlbl;
    private javax.swing.JLabel fblbl;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel optnlbl;
    private javax.swing.JLabel sdlbl;
    // End of variables declaration//GEN-END:variables
}
