/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travel;

import java.awt.Color;
import java.awt.Container;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;


/**
 *
 * @author nambi
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
   

    @Override
    public Container getContentPane() {
        return super.getContentPane(); //To change body of generated methods, choose Tools | Templates.
    }
    public Login() {
        initComponents();
        this.getContentPane().setBackground(Color.YELLOW);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginLbl1 = new javax.swing.JLabel();
        LoginLbl2 = new javax.swing.JLabel();
        Logname = new javax.swing.JLabel();
        LogEmail = new javax.swing.JLabel();
        LogDOB = new javax.swing.JLabel();
        LogPas = new javax.swing.JLabel();
        LogConpas = new javax.swing.JLabel();
        Proceedbtn = new javax.swing.JButton();
        Txtlogname = new javax.swing.JTextField();
        Txtlogemail = new javax.swing.JTextField();
        TxtlogDOB = new javax.swing.JTextField();
        Cancelbtn = new javax.swing.JButton();
        Pas = new javax.swing.JPasswordField();
        Conpas = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 0));

        LoginLbl1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        LoginLbl1.setForeground(new java.awt.Color(153, 0, 0));
        LoginLbl1.setText("WELCOME TO THE SIGN UP PAGE");

        LoginLbl2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        LoginLbl2.setForeground(new java.awt.Color(153, 0, 0));
        LoginLbl2.setText("ENTER THE DETAILS:");

        Logname.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        Logname.setForeground(new java.awt.Color(153, 0, 0));
        Logname.setText("NAME:");

        LogEmail.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        LogEmail.setForeground(new java.awt.Color(153, 0, 0));
        LogEmail.setText("E-MAIL:");

        LogDOB.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        LogDOB.setForeground(new java.awt.Color(153, 0, 0));
        LogDOB.setText("DOB:");

        LogPas.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        LogPas.setForeground(new java.awt.Color(153, 0, 0));
        LogPas.setText("PASSWORD:");

        LogConpas.setFont(new java.awt.Font("Cambria", 1, 13)); // NOI18N
        LogConpas.setForeground(new java.awt.Color(153, 0, 0));
        LogConpas.setText("CONFIRM PASSWORD:");

        Proceedbtn.setText("PROCEED");
        Proceedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedbtnActionPerformed(evt);
            }
        });

        Txtlogemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtlogemailActionPerformed(evt);
            }
        });

        Cancelbtn.setText("CANCEL");
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginLbl2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LogPas)
                                            .addComponent(LogDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Logname, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LogEmail))))
                                    .addComponent(LogConpas))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txtlogname, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(Txtlogemail, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(TxtlogDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(Pas)
                                    .addComponent(Conpas))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 54, Short.MAX_VALUE)
                        .addComponent(LoginLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(Proceedbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoginLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginLbl2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logname)
                    .addComponent(Txtlogname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogEmail)
                    .addComponent(Txtlogemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogDOB)
                    .addComponent(TxtlogDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogPas)
                    .addComponent(Pas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogConpas)
                    .addComponent(Conpas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proceedbtn)
                    .addComponent(Cancelbtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtlogemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtlogemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtlogemailActionPerformed

    private void ProceedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedbtnActionPerformed
        // TODO add your handling code here:
        String psw= new String(Pas.getPassword());
        String conpas = new String(Conpas.getPassword());
        if((Txtlogname.getText().trim().isEmpty())||(Txtlogemail.getText().trim().isEmpty())||(TxtlogDOB.getText().trim().isEmpty())||(Pas.getPassword().length==0)||(Conpas.getPassword().length==0))
        {
            JOptionPane.showMessageDialog(null, "Field is Empty");
        }
        else if(psw.equals(conpas))
        {
        try
        {
            String pas = new String(Pas.getPassword());
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mini1","root","(Hello123)");
            String sql="insert into user(Name,Email,Password) values(?, ?, ?)";
            PreparedStatement pstmt=conn.prepareStatement(sql);
            pstmt.setString(1,Txtlogname.getText());
            pstmt.setString(2, Txtlogemail.getText());
            //pstmt.setString(3,TxtlogDOB.getText());
            pstmt.setString(3,pas);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Insertion SUccessful!");
            conn.close(); 
            new Signup().setVisible(true);
            dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Passwords do not match!");
        }
    }//GEN-LAST:event_ProceedbtnActionPerformed

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JPasswordField Conpas;
    private javax.swing.JLabel LogConpas;
    private javax.swing.JLabel LogDOB;
    private javax.swing.JLabel LogEmail;
    private javax.swing.JLabel LogPas;
    private javax.swing.JLabel LoginLbl1;
    private javax.swing.JLabel LoginLbl2;
    private javax.swing.JLabel Logname;
    private javax.swing.JPasswordField Pas;
    private javax.swing.JButton Proceedbtn;
    private javax.swing.JTextField TxtlogDOB;
    private javax.swing.JTextField Txtlogemail;
    private javax.swing.JTextField Txtlogname;
    // End of variables declaration//GEN-END:variables
}
