/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travel;

/**
 *
 * @author nambi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Mainlbl1 = new javax.swing.JLabel();
        Mainlbl2 = new javax.swing.JLabel();
        Logbtn = new javax.swing.JButton();
        Signupbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(51, 153, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("WELCOME TO TRAVELLER'S STOP!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        Mainlbl1.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        Mainlbl1.setForeground(new java.awt.Color(102, 255, 255));
        Mainlbl1.setText("WELCOME TO TRAVELLER'S STOP!");
        getContentPane().add(Mainlbl1);
        Mainlbl1.setBounds(90, 10, 300, 20);

        Mainlbl2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Mainlbl2.setForeground(new java.awt.Color(102, 255, 255));
        Mainlbl2.setText("PLEASE CHOOSE ONE OPTION AMONG THE TWO PROVIDED.");
        getContentPane().add(Mainlbl2);
        Mainlbl2.setBounds(30, 50, 410, 20);

        Logbtn.setText("SINGUP");
        Logbtn.setOpaque(false);
        Logbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Logbtn);
        Logbtn.setBounds(190, 220, 90, 30);

        Signupbtn.setText("LOGIN");
        Signupbtn.setOpaque(false);
        Signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Signupbtn);
        Signupbtn.setBounds(190, 291, 90, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/travel/plane.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 450, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogbtnActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogbtnActionPerformed

    private void SignupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupbtnActionPerformed
        // TODO add your handling code here:
        new Signup().setVisible(true);
        dispose();
    }//GEN-LAST:event_SignupbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logbtn;
    private javax.swing.JLabel Mainlbl1;
    private javax.swing.JLabel Mainlbl2;
    private javax.swing.JButton Signupbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
