/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package travel;
import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author nambi
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    
    @Override
    public Container getContentPane() {
        return super.getContentPane(); //To change body of generated methods, choose Tools | Templates.
    }
    
    public Signup() {
        initComponents();
        this.getContentPane().setBackground(Color.YELLOW);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Signuplbl = new javax.swing.JLabel();
        Detlbl = new javax.swing.JLabel();
        Lblname = new javax.swing.JLabel();
        Paslbl = new javax.swing.JLabel();
        Signupbtn = new javax.swing.JButton();
        Txtuser = new javax.swing.JTextField();
        Txtpas = new javax.swing.JPasswordField();
        Cancelbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Signuplbl.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Signuplbl.setForeground(new java.awt.Color(102, 0, 0));
        Signuplbl.setText("WELCOME TO THE LOGIN PAGE!");

        Detlbl.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        Detlbl.setForeground(new java.awt.Color(102, 0, 0));
        Detlbl.setText("PLEASE ENTER YOUR DETAILS:");

        Lblname.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Lblname.setForeground(new java.awt.Color(102, 0, 0));
        Lblname.setText("USERNAME:");

        Paslbl.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Paslbl.setForeground(new java.awt.Color(102, 0, 0));
        Paslbl.setText("PASSWORD:");

        Signupbtn.setText("PROCEED");
        Signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupbtnActionPerformed(evt);
            }
        });

        Cancelbtn.setText("CANCEL");
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Signuplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Paslbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                        .addComponent(Lblname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Txtuser)
                                        .addComponent(Txtpas, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Signupbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Detlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Signuplbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Detlbl)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lblname)
                    .addComponent(Txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Paslbl)
                    .addComponent(Txtpas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Signupbtn)
                    .addComponent(Cancelbtn))
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupbtnActionPerformed
        // TODO add your handling code here:
        if((Txtuser.getText().trim().isEmpty())||(Txtpas.getPassword().length==0))
        {
            JOptionPane.showMessageDialog(null, "Field is Empty");
        }
        else
        {
        try
        {
            String pas = new String(Txtpas.getPassword());
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mini1","root","(Hello123)");
            String sql="Select Password from user where Name =?";
            PreparedStatement pstmt=conn.prepareStatement(sql);
            pstmt.setString(1,Txtuser.getText());
            //pstmt.setString(2,Txtpas.getPassword().toString());
            ResultSet rs = pstmt.executeQuery();
            while(rs.next())
            {
                String pas1 = rs.getString("Password");
                if(pas1.equals(pas))
                {
                    JOptionPane.showMessageDialog(null, "Login Successful!");
                    new Wayoftravel().setVisible(true);
                    dispose();
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Invalid Username or password");
                }
                
            }
            conn.close();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        } 
        }
        
    }//GEN-LAST:event_SignupbtnActionPerformed

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        dispose();
    }//GEN-LAST:event_CancelbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JLabel Detlbl;
    private javax.swing.JLabel Lblname;
    private javax.swing.JLabel Paslbl;
    private javax.swing.JButton Signupbtn;
    private javax.swing.JLabel Signuplbl;
    private javax.swing.JPasswordField Txtpas;
    public static javax.swing.JTextField Txtuser;
    // End of variables declaration//GEN-END:variables
}
